# theme = "tokyonight_moon"
theme = "nord_dark_transparent"

[editor]
line-number = "relative"
mouse = true
cursorline = true
auto-completion = true
auto-format = true
auto-info = true
color-modes = true
auto-pairs = true
gutters = ["diff", "diagnostics", "line-numbers", "spacer"]
middle-click-paste = true
bufferline = "multiple"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type", "version-control"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
enable = true
display-messages = true
auto-signature-help = true
display-inlay-hints = true
display-signature-help-docs = true
snippets = true

[keys.insert]
C-space = "completion"
